services:
  api:
    build:
      context: ../api
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - app
  agent:
    build:
      context: ../agent
    container_name: agent
    ports:
      - "5500:5500"
    env_file:
      - ../agent/.env
    networks:
      - app

  mcp:
    build:
      context: ../mcp
    container_name: mcp
    ports:
      - "8801:8801"
    env_file:
      - ../mcp/web_docs/.env
    networks:
      - app

networks:
  app:
    driver: bridge


